// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rteqgaepsychkvxagkkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0ZXFnYWVwc3ljaGt2eGFna2t6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0NDExMjUsImV4cCI6MjA3MTAxNzEyNX0.brvswmKgTa-CEsu-vYhuaQ8mFl-3Y2WD7Qsj8xgNNaU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});